config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:update]

  resources :users, only: [:update] do
  	post "downgrade"
  	get "downgrade"
  end

  resources :wikis
  resources :collaborations, only: [:create, :destroy]

  resources :charges, only: [:new, :create]
 
  root to: 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  def self.wikis
    Wiki.where(id: pluck(:wiki_id))
  end

  def self.users
    User.where(id: pluck(:user_id))
  end

  def user
    User.find(user_id)
  end

  def wiki
    Wiki.find(wiki_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborations
  has_many :wikis, through: :collaborations

  after_update :update_private_wikis

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def admin?
    role == 'admin'
  end

  protected

  def update_private_wikis
    return unless role_was == 'premium' && role == 'standard'
    wikis.all.update_all(wiki_private: false)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborations
  has_many :users, through: :collaborations

  validates :title, length: { minimum: 2 }, presence: true
  validates :body, length: { minimum: 10 }, presence: true
  validate :premium_user_creates_private_wiki, on: :create

  def public?
    wiki_private == false
  end

  protected

  def premium_user_creates_private_wiki
    return unless wiki_private
    errors.add(:base, 'Only premium user can create private wiki') unless user.premium? || user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    wikis_path
  end

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # rubocop:disable all:
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 1500,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    if current_user.update(role: 'premium')
      flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    else
      flash[:success] = 'There was an error upgrading your account. Please contact support!'
    end

    redirect_to edit_user_registration_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
  # rubocop:enable all

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: 1500
    }
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @users = params[:user_ids]
    @wiki = Wiki.find(params[:wiki_id])
    @users.each do |user|
      @wiki_collaboration = @wiki.collaborations.new(user_id: user)
      @wiki_collaboration.save
    end
    flash[:success] = 'Collaborator added.'
    redirect_to @wiki
  end

  def destroy
    @collaboration = Collaboration.find(params[:id])

    @collaboration.destroy

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
  end

  def downgrade
    if current_user.update(role: 'standard')
      flash[:notice] = 'Account downgraded successfully.'
    else
      flash[:error] = 'There was an error. Please try again.'
    end
    redirect_to edit_user_registration_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include Pundit

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user
    @wiki = Wiki.new(wiki_params)
    @wiki.user = @user

    authorize @wiki

    if @wiki.save
      redirect_to @wiki
    else
      flash[:error] = 'There was an error saving the wiki. Please try again.'
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = 'Wiki was updated.'
      redirect_to @wiki
    else
      flash[:error] = 'There was an error saving the wiki. Please try again.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = 'Wiki was deleted successfully.'
      redirect_to wikis_path
    else
      flash[:error] = 'There was an error deleting the wiki.'
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :wiki_private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown_wiki(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = { fenced_code_blocks: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
 	<div class='container'>
 	<div class="row">
   		<div class="col-md-4">
	   		<h2>Update Account</h2>
	   		<div style="width: 100%; height: 2px; background: #F87431; overflow: hidden;"></div>
		    <p>From blocipedia, the free encyclopedia.</p>
	   		<h3>Account details</h3>	   		
	   		<p><b>Name:</b> <%= current_user.name %>
	   		<p><b>Email:</b> <%= current_user.email %>
	   		<p><b>Created:</b> <%= current_user.created_at %>
	   		<p><b>Account type:</b> <%= current_user.role %><br>
            <% if current_user.standard? || current_user.admin? %>
                <hr><h3>Upgrade to premium</h3>
                <p>Premium users have the ability to create and view private wikis.</p>
		   		<script class='stripe-button' 
		           src="https://checkout.stripe.com/checkout.js" 
		           data-key="<%= @stripe_btn_data[:key] %>" 
		           data-amount=<%= @stripe_btn_data[:amount] %> 
		           data-description="<%= @stripe_btn_data[:description] %>" >
		    	</script>
		 	<% elsif current_user.premium? %>
		   		<p>You already have a premium account. Use the following link to downgrade to a standard level account:</p>
		   	    <%= link_to "Edit Account details", edit_user_registration_path %>
		 	<% end %>
 	<% end %>
	</div>
</div>
</div>

app/views/collaborations/add_remove_collaborations.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for wiki, url: collaborations_path, method: :post do %>
    <%= hidden_field_tag :wiki_id, wiki.id %>
  <% @users.each do |user| %>
    <% next if current_user == user %>
    <div class="checkbox">
    <%= check_box_tag "user_ids[]", user.id, wiki.users.include?(user) %>
    <%= user.username %>
      <% wiki.collaborations.each do |collaboration| %>
        <% if user.wiki_collaborations.include?(collaboration) %>
          <%= link_to "| Remove", collaboration, method: :delete %>
        <% end %>
      <% end %>
  </div>
  <% end %>

  <%= submit_tag 'Add Collaborators', class: 'btn btn-primary' %>

  </div>

<% end %>
</div>

app/views/collaborations/destroy.js.erb
$('#collaborations-' +<%= @collaboration.id %>).hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class='container'>
      <ul class='nav nav-tabs'>
        <li><%= link_to 'Blocipedia', root_path %></li>
        <li><%= link_to 'Public Wikis', wikis_path %></li>
        <% if current_user %> 
          <% if current_user.premium? %>
          <li><%= link_to 'Private Wikis', wikis_path %></li>
          <% end %>
        <% end %>
        <li><%= link_to 'Wikis', wikis_path %></li>
        <div class="pull-right user-info"> 
           <% if current_user %>
             Hello <%= current_user.name %> <%= link_to ' Sign out', destroy_user_session_path, method: :delete %>
               <%= link_to '| Update Account', new_charge_path %>
           <% else %>
             <%= link_to 'Sign In', new_user_session_path %> or
             <%= link_to 'Sign Up', new_user_registration_path %>
           <% end %>
         </div>
      </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:success] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:success] %>
      </div>    
      <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
</br>
<div class="container">
  <div class="jumbotron">
    <h1>Blocipedia</h1>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <h3><%= link_to 'Article 1', root_path %></h3>
      <p>This is a placeholder for a fragment of a wiki article.</p>
      <p>Clicking on the article title will link to the full wiki article.</p>
    </div>
    <div class="col-sm-4">
      <h3><%= link_to 'Article 2', root_path %></h3>
      <p>This is a placeholder for a fragment of a wiki article.</p>
      <p>Clicking on the article title will link to the full wiki article.</p>
    </div>
    <div class="col-sm-4">
      <h3><%= link_to 'Article 3', root_path %></h3>
      <p>This is a placeholder for a fragment of a wiki article.</p>
      <p>Clicking on the article title will link to the full wiki article.</p>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
   <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(@wiki.errors[:title]) do %>	
   <%= f.label :title %>
   <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
   <% end %>
   <%= form_group_tag(@wiki.errors[:title]) do %>	
   <%= f.label :body %>
   <%= f.text_area :body, rows: 12, class: 'form-control', placeholder: "Enter wiki body" %>
   <% end %>
   <% if policy(@wiki).create_private? %>
     <%= f.check_box :wiki_private, {}, true, false  %>
	 <%= f.label :wiki_private, "Make this a private wiki" %>
   <% end %>
 <br>
 <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
<% end %>

app/views/wikis/_wiki_html.erb
 <div class="row">
   <div class="col-md-8">
     <h3><%= @wiki.title %></h3>
     <div style="width: 100%; height: 2px; background: #F87431; overflow: hidden;"></div>
     <p>From blocipedia, the free encyclopedia.</p>
     <br>
     <p><%= @wiki.body %></p>
     <p>[Created by <b><%= @wiki.user.name %></b> (<%= @wiki.user.email %>) at <%= @wiki.created_at %>]</p>
   </div>
 <div class="col-md-8">
    <br>
    <% if policy(@wiki).create_private? %>
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
    <% end %>
 </div>
 </div>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p><b>Guidelines for wikis</b></p>
     <ul>
       <li>Content that violates any copyrights will be deleted. </li>
       <li>Encyclopedic content must be verifiable. </li>
       <li>Work submitted to Blocipedia can be edited, used, and redistributed—by anyone—subject to certain terms and conditions.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: {wiki: @wiki} %>
   </div>
 </div>

app/views/wikis/index.html.erb
</br>
<div class='container'>
<div class="row">
  <div class="col-md-8">
    <h2>Public Wikis</h2>
    <div style="width: 100%; height: 2px; background: #F87431; overflow: hidden;"></div>
    <p>From blocipedia, the free encyclopedia.</p>
    <div>
    <% if current_user %>
    </br><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    <% end %>
    </div><br>
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
        <% next if wiki.wiki_private == true unless wiki.user == current_user && current_user.premium? if current_user.nil? != false %>
          <h4 class="media-heading">
            <% if wiki.wiki_private == true %><b>[Private] </b><% end %>
            <%= link_to wiki.title, wiki %>
          </h4>
          <small>
            <%= markdown_wiki wiki.body %><br>
            <% if current_user %>
              <% if policy(wiki).edit? %>
              <%= link_to "Edit ", edit_wiki_path(wiki) %>
              <% end %>
              <% if policy(wiki).destroy? %>
              | <%= link_to " Delete", wiki, method: :delete, data: { confirm: 'Are you sure you want to delete this wiki?' } %>
              <% end %>
            <% end %>
            <br><br>
          </small>
        </div>
      </div>
    <% end %>
    <br><div style="width: 100%; height: 2px; background: #F87431; overflow: hidden;"></div>
    <br><br>
  </div>
</div>
</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 
 <div class='container'>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Content that violates any copyrights will be deleted. </li>
       <li>Encyclopedic content must be verifiable. </li>
       <li>Work submitted to Wikipedia can be edited, used, and redistributed—by anyone—subject to certain terms and conditions.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: {wiki: @wiki} %>
   </div>
 </div>
</div>

app/views/wikis/show.html.erb
<div class='container'>
 <div class="row">
   <div class="col-md-8">
     <h3><%= markdown_wiki @wiki.title %></h3>
     <div style="width: 100%; height: 2px; background: #F87431; overflow: hidden;"></div>
     <p>From blocipedia, the free encyclopedia.</p>
     <br>
     <p><%= markdown_wiki @wiki.body %></p>
     <p>[Created by <b><%= @wiki.user.name %></b> (<%= @wiki.user.email %>) at <%= @wiki.created_at %>]</p>
   </div>
 <div class="col-md-8">
    <br>
    <% if policy(@wiki).edit? %>
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
    <% end %>
 </div>
 </div>
  <br><br>
  <% if policy(@wiki).add_collaborator? %>
  <% if @wiki.users.count > 0 %>
      <b>Current Collaborators</b><br>
      <% @wiki.collaborations.each do |collaboration| %>
      <%= content_tag :div, class: 'media', id: "collaborations-#{collaboration.id}" do %>
        <%= collaboration.user.name %> |  
        <%= link_to " Remove ", collaboration, method: :delete, remote: true %><br>
        <% end %>
      <% end %>
    <% end %>
    <br><br>
    <% if @wiki.collaborations.count < User.count - 1 %>
    <h4>Add new collaborator</h4>  
    <%= form_for @wiki, url: collaborations_path, method: :post do %>
    <%= hidden_field_tag(:wiki_id, @wiki.id) %>
    <% @users.each do |user| %>
      <% next if current_user == user || @wiki.users.include?(user) %>
      <%= check_box_tag "user_ids[]", user.id %>
      <%= label_tag(user.id, user.name) %><br>
    <% end %>
    <br>
    <%= submit_tag 'Add Collaborators', class: 'btn btn-primary' %><br>
    </div>
  <% end %>
  <% end %> 
  </div>

  </div>
  <% end %>
</div>